function tx = init_n210_tx(txcfg, rf)
% init_n210_tx  Single-channel N210 transmitter (param-driven).
%   Used by node A (legitimate TX) and node C (jammer TX). N210 has a fixed
%   100 MHz master clock, so we set InterpolationFactor (not MasterClockRate)
%   and address by IPAddress (no SerialNum).
    tx = comm.SDRuTransmitter( ...
        'Platform',            txcfg.platform, ...
        'IPAddress',           txcfg.ipAddress, ...
        'CenterFrequency',     rf.fc, ...
        'Gain',                txcfg.gain, ...
        'InterpolationFactor', txcfg.interp, ...
        'ChannelMapping',      1);
    fprintf('N210 TX ready @ %s: fc=%.3f MHz, fs=%.3f MHz, gain=%g\n', ...
            txcfg.ipAddress, rf.fc/1e6, rf.fs/1e6, txcfg.gain);
end
