function rx = init_n210_rx(rxcfg, rf)
% init_n210_rx  N210 receiver in continuous streaming mode (param-driven).
%   Used by node B (victim) and node C (channel sensing). Mirrors the 2-node
%   init_usrp_rx but driven by an explicit rxcfg struct so the same helper
%   serves multiple radios.
    rx = comm.SDRuReceiver( ...
        'Platform',         rxcfg.platform, ...
        'IPAddress',        rxcfg.ipAddress, ...
        'CenterFrequency',  rf.fc, ...
        'Gain',             rxcfg.gain, ...
        'SamplesPerFrame',  rxcfg.samplesPerFrame, ...
        'DecimationFactor', rxcfg.deci, ...
        'OutputDataType',   'double');
    fprintf('N210 RX ready @ %s: fc=%.3f MHz, fs=%.3f MHz, gain=%g\n', ...
            rxcfg.ipAddress, rf.fc/1e6, rf.fs/1e6, rxcfg.gain);
end
