function tx = init_usrp_tx(params)
% init_usrp_tx  Build a dual-channel B210 transmitter from params.tx.
%   ch1 = real OFDM frame, ch2 = jammer (ChannelMapping [1 2]).
    p = params.tx;
    tx = comm.SDRuTransmitter( ...
        'Platform',            p.platform, ...
        'SerialNum',           p.serialNum, ...
        'CenterFrequency',     p.fc, ...
        'Gain',                p.gain, ...
        'MasterClockRate',     p.masterClockRate, ...
        'InterpolationFactor', p.interpFactor, ...
        'ChannelMapping',      p.channelMapping);
    fprintf('B210 transmitter ready: fc=%.3f MHz, fs=%.3f MHz\n', ...
            p.fc/1e6, p.fs/1e6);
end
