function rx = init_usrp_rx(params)
% init_usrp_rx  Build the N210 receiver in continuous streaming mode.
    p = params.rx;
    rx = comm.SDRuReceiver( ...
        'Platform',         p.platform, ...
        'IPAddress',        p.ipAddress, ...
        'CenterFrequency',  p.fc, ...
        'Gain',             p.gain, ...
        'SamplesPerFrame',  p.samplesPerFrame, ...
        'DecimationFactor', p.deci, ...
        'OutputDataType',   'double');
    fprintf('N210 receiver ready: fc=%.3f MHz, fs=%.3f MHz\n', ...
            p.fc/1e6, p.fs/1e6);
end
